### ISSUE TITLE
Niemals Fremde VariablenProfile mit nutzen

### ISSUE THREAD

**Issue by Nall-chan** [Wolbolar/IPSymconTPLinkHS110#1]
https://github.com/Wolbolar/IPSymconTPLinkHS110/blob/986c565b470320ea33f24ed8cdc9e235ca418669/TP%20Link%20HS%20Device/module.php#L45

***.HM Profile gehören zu Homematic Instanzen und sind in IPS NICHT immer verfügbar.
Sondern nur wenn eine entsprechende Homematic-Instanz diese erzeugt hat, ähnlich wie bei PHP-Modulen.
Immer eigene Profile mitliefern, sonst gibt es Fehler.
Siehe:
https://www.symcon.de/forum/threads/36489-PHP-Modul-TP-Link-HS-100-TP-Link-HS-100?p=361280#post361280

**Comment by Wolbolar** [comment]
Ich hoffe das passt jetzt, habe die Profile ausgetaucht gegen spezifische Profile.
